### ISSUE TITLE
BACKEND: Messaging server endpoints

### ISSUE THREAD

**Issue by Kushan-Nilanga** [Kushan-Nilanga/reinflow#16]
- [x] ENDPOINT: Fetch data from messaging server & store it in database
- [x] ENDPOINT: Send control commands to messaging server
- [x] Documentation
- [x] Tests

**Comment by JakeRoussis** [comment]
I'll probably jump on this ticket once I address the other one I'm assigned to.

**Comment by SheronSuditha** [comment]
- Updated socket.io server and sensor connections

**Comment by SheronSuditha** [comment]
+ added the endpoint for sensor1 
_endpoint is fully functional and updates every 5 seconds once socket server and clients deployed_
