### ISSUE TITLE
MESSAGING SERVER: Endpoints

### ISSUE THREAD

**Issue by Kushan-Nilanga** [Kushan-Nilanga/reinflow#21]
- [x] ENDPOINT: Send random value for the vehicle density when requested by BACKEND(value, id)
- [x] ENDPOINT: Receive action commands from BACKEND
- [ ] DOCUMENTATION
- [ ] TESTS

**Comment by JakeRoussis** [comment]
Easy enough to send a random value but what is going to trigger the value to be sent? Is it when a particular page is loaded. When a button is clicked?

**Comment by JakeRoussis** [comment]
@Kushan-Nilanga @SheronSuditha @nishalaha Thoughts guys on previous question?

**Comment by Kushan-Nilanga** [comment]
Yeah. Sorry I thought I send a response. Idea was to build some sort of a memory buffer in in backend-express. So there should be a GET endpoint which will take in the id in the url (GET http://localhost:8000/sensors/:sensorId). What is your thoughts on this?

**Comment by JakeRoussis** [comment]
This sounds reasonable enough for this particular sprint. Thanks

**Comment by SheronSuditha** [comment]
Pretty much via the memory buffer we will be able to get data to our front end and the algorithms. The sensors will be constantly keeping that bit of the platform always upto date and active. Which means the socket server and the sensors will be connected and the sensors will update the socket server with real-time data.
