### ISSUE TITLE
Socket.io server setup

### ISSUE THREAD

**Issue by Kushan-Nilanga** [Kushan-Nilanga/reinflow#6]
Setup boilerplate for socket.io server and API

MQTT API should store and update the number of vehicles recorded by an underground sensor periodically(This can be a random number recorded every 15 seconds). Then it should implement an endpoint that backend API can call and retrieve the recorded vehicle number. Then it should contain a `post` endpoint so backend API can control the traffic lights.

- [x] Project setup

**Comment by SheronSuditha** [comment]
- [x] Broiler-plate setup

Added the related boilerplate code, installed socket.io, express and http. 
_Clients will be able to connect on port 5000 locally as of now._

**Comment by Kushan-Nilanga** [comment]
Hey team. Please give me an update on the status of this pull request.
Cheers.

**Comment by SheronSuditha** [comment]
Server Boilerplate is complete, its just with regards to the client(Sensors) side. 
We should be all good to proceed.
