### ISSUE TITLE
BACKEND: Detailing endpoints and Admin Endpoints

### ISSUE THREAD

**Issue by SheronSuditha** [Kushan-Nilanga/reinflow#74]
I have added folders for endpoint security

### Access Level1 `routes/accesslevel1/`
For top level administration (removing users, promoting/demoting users) with level2 and level3 access inclusive

- [x] GET: all users
- [x] POST: promote/demote users
- [x] POST: Manual control or automatic control for lights

### Access Level2 `routes/accesslevel2/`
For mid level administration (Visualising further statistics about traffic, adding and removing sensors/lights, edit sensors) with level3 access inclusive
- [x] GET: all sensors
- [x] POST: changes to sensors
- [x] GET: all lights
- [x] POST: changes to lights
- [x] POST: add lights
- [x] POST: add sensors

### Access Level3 `routes/accesslevel3/`
For low level access (Visualising traffic light data, visualising sensor data)
- [x] - GET: sensor data
- [x] - GET: light data
- [x] - POST: change name
- [x] - POST: change password

**Comment by Kushan-Nilanga** [comment]
I will start looking into admin endpoints

**Comment by SheronSuditha** [comment]
+ Updated frontend endpoints
_Added AccessControl Endpoint_

**Comment by SheronSuditha** [comment]
_Completed_
